server:
  port: ${port.coinstore}

accountServiceUrl: http://${host.coinstore}:${port.coinstore}

spring:
    data:
        mongodb:
            host: ${host.mongodb}
            port: ${port.mongodb}
            database: zjhlearn
zooKeeper:
    hosts: ${zooKeeperHosts}
    project: ${projectName}
    service: ${service.coinstore}
    port: ${port.coinstore}
