server:
  port: ${port.core}

spring:
    data:
        mongodb:
            host: ${host.mongodb}
            port: ${port.mongodb}
            database: zjhlearn

zooKeeper:
    hosts: ${zooKeeperHosts}
    project: ${projectName}
    service: ${service.core}
    port: ${port.core}
